// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/v1/user_err.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserError int32

const (
	UserError_User_UNSPECIFIED UserError = 0
	UserError_USER_NOT_FOUND   UserError = 1
)

// Enum value maps for UserError.
var (
	UserError_name = map[int32]string{
		0: "User_UNSPECIFIED",
		1: "USER_NOT_FOUND",
	}
	UserError_value = map[string]int32{
		"User_UNSPECIFIED": 0,
		"USER_NOT_FOUND":   1,
	}
)

func (x UserError) Enum() *UserError {
	p := new(UserError)
	*p = x
	return p
}

func (x UserError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserError) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_err_proto_enumTypes[0].Descriptor()
}

func (UserError) Type() protoreflect.EnumType {
	return &file_user_v1_user_err_proto_enumTypes[0]
}

func (x UserError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserError.Descriptor instead.
func (UserError) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_err_proto_rawDescGZIP(), []int{0}
}

var File_user_v1_user_err_proto protoreflect.FileDescriptor

const file_user_v1_user_err_proto_rawDesc = "" +
	"\n" +
	"\x16user/v1/user_err.proto\x12\vapi.user.v1*5\n" +
	"\tUserError\x12\x14\n" +
	"\x10User_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x01B:Z8github.com/LEILEI0628/GoWeb-MicroServices/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_err_proto_rawDescOnce sync.Once
	file_user_v1_user_err_proto_rawDescData []byte
)

func file_user_v1_user_err_proto_rawDescGZIP() []byte {
	file_user_v1_user_err_proto_rawDescOnce.Do(func() {
		file_user_v1_user_err_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_err_proto_rawDesc), len(file_user_v1_user_err_proto_rawDesc)))
	})
	return file_user_v1_user_err_proto_rawDescData
}

var file_user_v1_user_err_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_user_err_proto_goTypes = []any{
	(UserError)(0), // 0: api.user.v1.UserError
}
var file_user_v1_user_err_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_err_proto_init() }
func file_user_v1_user_err_proto_init() {
	if File_user_v1_user_err_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_err_proto_rawDesc), len(file_user_v1_user_err_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_user_err_proto_goTypes,
		DependencyIndexes: file_user_v1_user_err_proto_depIdxs,
		EnumInfos:         file_user_v1_user_err_proto_enumTypes,
	}.Build()
	File_user_v1_user_err_proto = out.File
	file_user_v1_user_err_proto_goTypes = nil
	file_user_v1_user_err_proto_depIdxs = nil
}
