// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: interactive/v1/interactive_err.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractiveError int32

const (
	// 0: 未知错误
	InteractiveError_INTERACTIVE_UNSPECIFIED InteractiveError = 0
)

// Enum value maps for InteractiveError.
var (
	InteractiveError_name = map[int32]string{
		0: "INTERACTIVE_UNSPECIFIED",
	}
	InteractiveError_value = map[string]int32{
		"INTERACTIVE_UNSPECIFIED": 0,
	}
)

func (x InteractiveError) Enum() *InteractiveError {
	p := new(InteractiveError)
	*p = x
	return p
}

func (x InteractiveError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractiveError) Descriptor() protoreflect.EnumDescriptor {
	return file_interactive_v1_interactive_err_proto_enumTypes[0].Descriptor()
}

func (InteractiveError) Type() protoreflect.EnumType {
	return &file_interactive_v1_interactive_err_proto_enumTypes[0]
}

func (x InteractiveError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractiveError.Descriptor instead.
func (InteractiveError) EnumDescriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_err_proto_rawDescGZIP(), []int{0}
}

var File_interactive_v1_interactive_err_proto protoreflect.FileDescriptor

const file_interactive_v1_interactive_err_proto_rawDesc = "" +
	"\n" +
	"$interactive/v1/interactive_err.proto\x12\x12api.interactive.v1*/\n" +
	"\x10InteractiveError\x12\x1b\n" +
	"\x17INTERACTIVE_UNSPECIFIED\x10\x00BAZ?github.com/LEILEI0628/GoWeb-MicroServices/api/interactive/v1;v1b\x06proto3"

var (
	file_interactive_v1_interactive_err_proto_rawDescOnce sync.Once
	file_interactive_v1_interactive_err_proto_rawDescData []byte
)

func file_interactive_v1_interactive_err_proto_rawDescGZIP() []byte {
	file_interactive_v1_interactive_err_proto_rawDescOnce.Do(func() {
		file_interactive_v1_interactive_err_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interactive_v1_interactive_err_proto_rawDesc), len(file_interactive_v1_interactive_err_proto_rawDesc)))
	})
	return file_interactive_v1_interactive_err_proto_rawDescData
}

var file_interactive_v1_interactive_err_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interactive_v1_interactive_err_proto_goTypes = []any{
	(InteractiveError)(0), // 0: api.interactive.v1.InteractiveError
}
var file_interactive_v1_interactive_err_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interactive_v1_interactive_err_proto_init() }
func file_interactive_v1_interactive_err_proto_init() {
	if File_interactive_v1_interactive_err_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interactive_v1_interactive_err_proto_rawDesc), len(file_interactive_v1_interactive_err_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interactive_v1_interactive_err_proto_goTypes,
		DependencyIndexes: file_interactive_v1_interactive_err_proto_depIdxs,
		EnumInfos:         file_interactive_v1_interactive_err_proto_enumTypes,
	}.Build()
	File_interactive_v1_interactive_err_proto = out.File
	file_interactive_v1_interactive_err_proto_goTypes = nil
	file_interactive_v1_interactive_err_proto_depIdxs = nil
}
