// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: interactive/v1/interactive.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInteractiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInteractiveRequest) Reset() {
	*x = CreateInteractiveRequest{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInteractiveRequest) ProtoMessage() {}

func (x *CreateInteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInteractiveRequest.ProtoReflect.Descriptor instead.
func (*CreateInteractiveRequest) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{0}
}

type CreateInteractiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInteractiveReply) Reset() {
	*x = CreateInteractiveReply{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInteractiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInteractiveReply) ProtoMessage() {}

func (x *CreateInteractiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInteractiveReply.ProtoReflect.Descriptor instead.
func (*CreateInteractiveReply) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{1}
}

type UpdateInteractiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInteractiveRequest) Reset() {
	*x = UpdateInteractiveRequest{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInteractiveRequest) ProtoMessage() {}

func (x *UpdateInteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInteractiveRequest.ProtoReflect.Descriptor instead.
func (*UpdateInteractiveRequest) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{2}
}

type UpdateInteractiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInteractiveReply) Reset() {
	*x = UpdateInteractiveReply{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInteractiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInteractiveReply) ProtoMessage() {}

func (x *UpdateInteractiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInteractiveReply.ProtoReflect.Descriptor instead.
func (*UpdateInteractiveReply) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{3}
}

type DeleteInteractiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInteractiveRequest) Reset() {
	*x = DeleteInteractiveRequest{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInteractiveRequest) ProtoMessage() {}

func (x *DeleteInteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInteractiveRequest.ProtoReflect.Descriptor instead.
func (*DeleteInteractiveRequest) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{4}
}

type DeleteInteractiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInteractiveReply) Reset() {
	*x = DeleteInteractiveReply{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInteractiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInteractiveReply) ProtoMessage() {}

func (x *DeleteInteractiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInteractiveReply.ProtoReflect.Descriptor instead.
func (*DeleteInteractiveReply) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{5}
}

type GetInteractiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractiveRequest) Reset() {
	*x = GetInteractiveRequest{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractiveRequest) ProtoMessage() {}

func (x *GetInteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractiveRequest.ProtoReflect.Descriptor instead.
func (*GetInteractiveRequest) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{6}
}

type GetInteractiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractiveReply) Reset() {
	*x = GetInteractiveReply{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractiveReply) ProtoMessage() {}

func (x *GetInteractiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractiveReply.ProtoReflect.Descriptor instead.
func (*GetInteractiveReply) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{7}
}

type ListInteractiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInteractiveRequest) Reset() {
	*x = ListInteractiveRequest{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInteractiveRequest) ProtoMessage() {}

func (x *ListInteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInteractiveRequest.ProtoReflect.Descriptor instead.
func (*ListInteractiveRequest) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{8}
}

type ListInteractiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInteractiveReply) Reset() {
	*x = ListInteractiveReply{}
	mi := &file_interactive_v1_interactive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInteractiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInteractiveReply) ProtoMessage() {}

func (x *ListInteractiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactive_v1_interactive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInteractiveReply.ProtoReflect.Descriptor instead.
func (*ListInteractiveReply) Descriptor() ([]byte, []int) {
	return file_interactive_v1_interactive_proto_rawDescGZIP(), []int{9}
}

var File_interactive_v1_interactive_proto protoreflect.FileDescriptor

const file_interactive_v1_interactive_proto_rawDesc = "" +
	"\n" +
	" interactive/v1/interactive.proto\x12\x12api.interactive.v1\"\x1a\n" +
	"\x18CreateInteractiveRequest\"\x18\n" +
	"\x16CreateInteractiveReply\"\x1a\n" +
	"\x18UpdateInteractiveRequest\"\x18\n" +
	"\x16UpdateInteractiveReply\"\x1a\n" +
	"\x18DeleteInteractiveRequest\"\x18\n" +
	"\x16DeleteInteractiveReply\"\x17\n" +
	"\x15GetInteractiveRequest\"\x15\n" +
	"\x13GetInteractiveReply\"\x18\n" +
	"\x16ListInteractiveRequest\"\x16\n" +
	"\x14ListInteractiveReply2\xa9\x04\n" +
	"\vInteractive\x12m\n" +
	"\x11CreateInteractive\x12,.api.interactive.v1.CreateInteractiveRequest\x1a*.api.interactive.v1.CreateInteractiveReply\x12m\n" +
	"\x11UpdateInteractive\x12,.api.interactive.v1.UpdateInteractiveRequest\x1a*.api.interactive.v1.UpdateInteractiveReply\x12m\n" +
	"\x11DeleteInteractive\x12,.api.interactive.v1.DeleteInteractiveRequest\x1a*.api.interactive.v1.DeleteInteractiveReply\x12d\n" +
	"\x0eGetInteractive\x12).api.interactive.v1.GetInteractiveRequest\x1a'.api.interactive.v1.GetInteractiveReply\x12g\n" +
	"\x0fListInteractive\x12*.api.interactive.v1.ListInteractiveRequest\x1a(.api.interactive.v1.ListInteractiveReplyBAZ?github.com/LEILEI0628/GoWeb-MicroServices/api/interactive/v1;v1b\x06proto3"

var (
	file_interactive_v1_interactive_proto_rawDescOnce sync.Once
	file_interactive_v1_interactive_proto_rawDescData []byte
)

func file_interactive_v1_interactive_proto_rawDescGZIP() []byte {
	file_interactive_v1_interactive_proto_rawDescOnce.Do(func() {
		file_interactive_v1_interactive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interactive_v1_interactive_proto_rawDesc), len(file_interactive_v1_interactive_proto_rawDesc)))
	})
	return file_interactive_v1_interactive_proto_rawDescData
}

var file_interactive_v1_interactive_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_interactive_v1_interactive_proto_goTypes = []any{
	(*CreateInteractiveRequest)(nil), // 0: api.interactive.v1.CreateInteractiveRequest
	(*CreateInteractiveReply)(nil),   // 1: api.interactive.v1.CreateInteractiveReply
	(*UpdateInteractiveRequest)(nil), // 2: api.interactive.v1.UpdateInteractiveRequest
	(*UpdateInteractiveReply)(nil),   // 3: api.interactive.v1.UpdateInteractiveReply
	(*DeleteInteractiveRequest)(nil), // 4: api.interactive.v1.DeleteInteractiveRequest
	(*DeleteInteractiveReply)(nil),   // 5: api.interactive.v1.DeleteInteractiveReply
	(*GetInteractiveRequest)(nil),    // 6: api.interactive.v1.GetInteractiveRequest
	(*GetInteractiveReply)(nil),      // 7: api.interactive.v1.GetInteractiveReply
	(*ListInteractiveRequest)(nil),   // 8: api.interactive.v1.ListInteractiveRequest
	(*ListInteractiveReply)(nil),     // 9: api.interactive.v1.ListInteractiveReply
}
var file_interactive_v1_interactive_proto_depIdxs = []int32{
	0, // 0: api.interactive.v1.Interactive.CreateInteractive:input_type -> api.interactive.v1.CreateInteractiveRequest
	2, // 1: api.interactive.v1.Interactive.UpdateInteractive:input_type -> api.interactive.v1.UpdateInteractiveRequest
	4, // 2: api.interactive.v1.Interactive.DeleteInteractive:input_type -> api.interactive.v1.DeleteInteractiveRequest
	6, // 3: api.interactive.v1.Interactive.GetInteractive:input_type -> api.interactive.v1.GetInteractiveRequest
	8, // 4: api.interactive.v1.Interactive.ListInteractive:input_type -> api.interactive.v1.ListInteractiveRequest
	1, // 5: api.interactive.v1.Interactive.CreateInteractive:output_type -> api.interactive.v1.CreateInteractiveReply
	3, // 6: api.interactive.v1.Interactive.UpdateInteractive:output_type -> api.interactive.v1.UpdateInteractiveReply
	5, // 7: api.interactive.v1.Interactive.DeleteInteractive:output_type -> api.interactive.v1.DeleteInteractiveReply
	7, // 8: api.interactive.v1.Interactive.GetInteractive:output_type -> api.interactive.v1.GetInteractiveReply
	9, // 9: api.interactive.v1.Interactive.ListInteractive:output_type -> api.interactive.v1.ListInteractiveReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interactive_v1_interactive_proto_init() }
func file_interactive_v1_interactive_proto_init() {
	if File_interactive_v1_interactive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interactive_v1_interactive_proto_rawDesc), len(file_interactive_v1_interactive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interactive_v1_interactive_proto_goTypes,
		DependencyIndexes: file_interactive_v1_interactive_proto_depIdxs,
		MessageInfos:      file_interactive_v1_interactive_proto_msgTypes,
	}.Build()
	File_interactive_v1_interactive_proto = out.File
	file_interactive_v1_interactive_proto_goTypes = nil
	file_interactive_v1_interactive_proto_depIdxs = nil
}
